### ISSUE TITLE
"segment fault" on Geant4 format

### ISSUE THREAD

**Issue by vagnercassola** [haeginh/POLY2TET#2]
Dear Haegin Han,

Thanks for your share your amazing work. 

I'm trying to use the geant4 format on (geant4.10.06.p02), but I'm getting "segment fault" when the physics are loading. 
![Captura de tela de 2021-08-01 16-15-06](https://user-images.githubusercontent.com/68907497/127782767-d42d5a8c-1aca-449c-bd6b-b850cf86b054.png)
 
The error seems to be connected with the materials of parameterized volume, maybe I'm creating the ".material" file wrong - I didn't find an example of how to create it. For example, when I changed the "TetParameterisation::ComputeMaterial" to return an simple material without using the "tetData->GetMaterial" the code works fine. 

Could you, please, check my input files (it's just an sphere of water)? [sphere.zip](https://github.com/haeginh/POLY2TET/files/6913223/sphere.zip) 
 
I think, would be great if you could share an simple example with 1, 2 or more 3D objects, so we could test if the code is running ok.

Kind regards
Vagner

PS: On "init_vis.mac", the source setting file (source.mac) is missing.

**Comment by haeginh** [comment]
Dear Vagner,

Thank you for pointing out the missing source.mac file. I changed the code not to use source.mac for visualization and I also changed the README file accordingly.

For the core dump, I agree with you: it may because of the wrong material file.
A mentioned in the article paper, you should provide material file in MCNP format (or PHITS format).
In your case, this will look like this:
```
C water 1.00 g/cm3
m100 1000 -0.11190
          8000 -0.88810
```
I think this may be confusing for the users who dose not use MCNP. I will put this example on the README file as well :-)
Please let me know if you have further questions.

Best regards,
Haegin

**Comment by vagnercassola** [comment]
Dear Haegin,

Thank you for replying. I was not aware about the MCNP format (or PHITS format), I have never used these codes, I only have experience in GEANT4 and EGSnrc :-)

I made the changes and the code seems to work perfectly (yay!). Now, I'll do more tests with other phantoms ;-) 

With thanks,
Vagner
